export type Gender = "female" | "male" | "transgender";

export type SharingPreference =
  | "same_gender_only" // hard constraint
  | "no_preference" // no constraint
  | "companion" // pair with a named co-passenger on the same booking
  | "prefer_same_gender"; // soft: honoured when possible, never blocks confirmation

export type StationCode = string;
export type ISODateTime = string;
export type TravelClass = string;
export type BerthId = string;

export interface Passenger {
  id: string;
  displayName: string; // obviously synthetic
  gender: Gender;
  age: number;
  isMinor: boolean; // age < 18
  travellingAlone: boolean;
}

export interface Train {
  number: string; // synthetic, must not collide with a real train number
  name: string;
  from: StationCode;
  to: StationCode;
  departure: ISODateTime;
  arrival: ISODateTime;
  isOvernight: boolean; // drives the safety framing
  classes: TravelClass[];
}

export interface Coach {
  id: string;
  class: TravelClass;
  sideLowerBerths: BerthId[]; // the RAC-shareable berths
  fullBerths: BerthId[];
}

export interface RacEntry {
  position: number; // queue order at booking
  passenger: Passenger;
  preference: SharingPreference;
  boardingStation: StationCode;
  alightingStation: StationCode;
  bookedAt: ISODateTime;
}

export interface ConstraintResult {
  name: string;
  satisfied: boolean;
  detail: string;
}

export interface Pairing {
  berthId: BerthId;
  occupants: [RacEntry, RacEntry?];
  constraintsSatisfied: ConstraintResult[];
  preferenceViolated: boolean;
  explanation: string; // generated by the solver, not the LLM
}

export interface FareBreakdown {
  totalFare: number;
  refundablePortion: number;
  currency: "INR";
}

export interface Booking {
  pnr: string; // synthetic format, visibly not a real PNR
  train: Train;
  passengers: Passenger[];
  status: "RAC" | "CNF" | "WL";
  racPosition?: number;
  fare: FareBreakdown;
  createdAt: ISODateTime;
}
